apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-cp
spec:
  destination:
    name: ''
    namespace: ''
    server: 'https://kubernetes.default.svc'
  source:
    path: multitenancy/multiple-cp/1-controlplane
    repoURL: 'https://github.com/kfaseela/gitops.git'
    targetRevision: HEAD
    directory:
      recurse: true
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
