apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-cp-2
spec:
  destination:
    name: ''
    namespace: ''
    server: 'https://kubernetes.default.svc'
  source:
    path: multitenancy/multiple-cp/tenant-2
    repoURL: 'https://github.com/kfaseela/gitops.git'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
